version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 63790:6379

  backend:
    image: golang:1.20
    entrypoint: .docker/entrypoint.sh
    container_name: backend
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    environment:
      - API_PORT=3333
      - API_DB_URL=redis://@redis:63790
      - API_DB_PASSWORD=''